version: '3.3'

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    web:
        build: .
        command: uwsgi --http :8000 --wsgi-file ./app/wsgi.py
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    backend-worker-1:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    worker:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    beat:
        build: .
        command: celery -A app beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    redis:
        image: redis:latest
        ports:
            - 6379:6379
