version: '3.8'

services:
    web:
        build: .
        command: uwsgi --ini uwsgi.ini
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - redis

    backend-worker-1:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    worker:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis

    beat:
        build: .
        command: celery -A app beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis

    redis:
        image: redis:latest
        ports:
            - 6379:6379
