version: '3.3'

services:
    db:
        image: postgres
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./data/db:/var/lib/postgresql/data

    web:
        build: .
        command: uwsgi --http :8000 --wsgi-file ./app/wsgi.py
        volumes:
            - .:/code
            - shared_sockets:/sockets  
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - db
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    backend-worker:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    
    beat:
        build: .
        command: celery -A app beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0

    redis:
        image: redis:latest
        ports:
            - 6380:6397

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 호스트의 nginx.conf 파일을 마운트
            - shared_sockets:/sockets  
        depends_on:
            - web

volumes:
    shared_sockets:
