version: '3.8'

services:
    web:
        build: .
        command: uwsgi --ini uwsgi.ini
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        depends_on:
            - redis

    worker:
        build: .
        command: celery -A app worker --loglevel=info
        volumes:
            - .:/code
        depends_on:
            - redis

    beat:
        build: .
        command: celery -A app beat --loglevel=info
        volumes:
            - .:/code
        depends_on:
            - redis

    redis:
        image: redis:latest
