# Generated by Django 4.2.3 on 2023-07-27 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0002_conversation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
