# Generated by Django 4.2.3 on 2023-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_chats",
            field=models.IntegerField(default=0),
        ),
    ]
